language: python
python:
- '3.8'
dist: bionic
os: linux
arch:
  - arm64
jobs:
  fast_finish: true

before_install:
- pip install poetry
install:
- poetry install
script:
- black --check .
- coverage run --source=eopsin -m pytest eopsin/tests
# the samples from the README file
- >
  coverage run -a --source=eopsin -m eopsin eval examples/smart_contracts/assert_sum.py "{\"int\": 4}" "{\"int\": 38}" "{\"constructor\": 6, \"fields\": []}"
- >
  coverage run -a --source=eopsin -m eopsin compile examples/smart_contracts/assert_sum.py > assert_sum.uplc
- >
  coverage run -a --source=eopsin -m eopsin eval_uplc examples/smart_contracts/assert_sum.py "{\"int\": 4}" "{\"int\": 38}" "{\"constructor\": 6, \"fields\": []}"
- >
  coverage run -a --source=eopsin -m eopsin compile_pluto examples/smart_contracts/assert_sum.py
- >
  coverage run -a --source=eopsin -m eopsin build examples/smart_contracts/assert_sum.py

after_success:
- coverage report
- coveralls
