language: python
python:
- '3.8'
- '3.9'
- '3.10'
- '3.11'
dist: bionic
os: linux
arch:
  - arm64
jobs:
  fast_finish: true

before_install:
- pip install poetry
install:
- poetry install
script:
- black --check .
- coverage run --source=opshin -m pytest opshin/tests
# the samples from the README file
- >
  coverage run -a --source=opshin -m opshin eval examples/smart_contracts/assert_sum.py "{\"int\": 4}" "{\"int\": 38}" "{\"constructor\": 6, \"fields\": []}"
- >
  coverage run -a --source=opshin -m opshin compile examples/smart_contracts/assert_sum.py > assert_sum.uplc
- >
  coverage run -a --source=opshin -m opshin eval_uplc examples/smart_contracts/assert_sum.py "{\"int\": 4}" "{\"int\": 38}" "{\"constructor\": 6, \"fields\": []}"
- >
  coverage run -a --source=opshin -m opshin compile_pluto examples/smart_contracts/assert_sum.py
- >
  coverage run -a --source=opshin -m opshin build examples/smart_contracts/assert_sum.py

after_success:
- coverage report
- coveralls
